name: fortuna_reader
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  sensors_plus: ^5.0.0
  share_plus: ^10.0.2
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  audio_session: ^0.1.19
  firebase_core: ^4.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/omikuji/fortunes.json
    # ğŸµ BGMãƒ•ã‚¡ã‚¤ãƒ«
    - assets/audio/n59.mp3
    - assets/audio/sfx_shake.mp3      # ç®±ã‚’æŒ¯ã‚‹
    - assets/audio/sfx_stick.mp3      # æ£’ãŒå½“ãŸã‚‹

    # ğŸ–¼ï¸ ç”»åƒé¡
    - assets/images/palm.png
    - assets/images/zodiac.png
    - assets/images/daily.png
    - assets/images/omikuji.png
    - assets/images/omikuji_bg.png

  # ãƒ•ã‚©ãƒ³ãƒˆã‚’è¿½åŠ ã™ã‚‹å ´åˆã¯ã“ã“ã«è¿½è¨˜
  # fonts:
  #   - family: NotoSansJP
  #     fonts:
  #       - asset: assets/fonts/NotoSansJP-Regular.ttf
  #       - asset: assets/fonts/NotoSansJP-Bold.ttf
